### YamlMime:QSharpType
uid: microsoft.quantum.canon.compose
name: Compose
type: function
namespace: microsoft.quantum.canon
summary: >-
  Két függvény összeállítását adja vissza.


  A $f $ és a $g $ függvényben a megadott függvények egy új függvényt adnak vissza, amely az $f \circ g $ értéket jelképezi.
syntax: "function Compose (outer : ('U -> 'V), inner : ('T -> 'U)) : ('T -> 'V)"
input:
  content: "(outer : ('U -> 'V), inner : ('T -> 'U))"
  types:
  - name: outer
    summary: Az alkalmazni kívánt második függvény.
    isFunction: true
    input:
      types:
      - uid: "'U"
        isLocal: true
    output:
      types:
      - uid: "'V"
        isLocal: true
  - name: inner
    summary: Az elsőként alkalmazandó függvény.
    isFunction: true
    input:
      types:
      - uid: "'T"
        isLocal: true
    output:
      types:
      - uid: "'U"
        isLocal: true
output:
  content: ('T -> 'V)
  types:
  - summary: Egy új függvény $h $, amely minden bemenethez $x $, $f (g (x)) = h (x) $.
    isFunction: true
    input:
      types:
      - uid: "'T"
        isLocal: true
    output:
      types:
      - uid: "'V"
        isLocal: true
typeParameters:
- uid: "'T"
  summary: Az elsőként alkalmazandó függvény bemeneti típusa.
- uid: "'U"
  summary: Az elsőként alkalmazandó függvény kimeneti típusa és az alkalmazandó második függvény bemeneti típusa.
- uid: "'V"
  summary: Az alkalmazni kívánt második függvény kimeneti típusa.
metadata:
  ms.openlocfilehash: f2e4d8d10e8113101a5d0ec1f37f8bb7cd0945c0
  ms.sourcegitcommit: 685a8ab16d7e6a25e63a168d6e7c385fa6e876cc
  ms.translationtype: MT
  ms.contentlocale: hu-HU
  ms.lasthandoff: 09/29/2020
  ms.locfileid: "91467171"
