### YamlMime:QSharpType
uid: microsoft.quantum.canon.compose
name: Compose
type: function
namespace: Microsoft.Quantum.Canon
summary: >-
  Két függvény összeállítását hozza létre.


  Ez azt jelenti, hogy a két függvény $f $ és $g $, egy új függvényt ad vissza, amely az $f \circ g $ értéket jelképezi.
syntax: "function Compose (outer : ('U -> 'V), inner : ('T -> 'U)) : ('T -> 'V)"
input:
  content: "(outer : ('U -> 'V), inner : ('T -> 'U))"
  types:
  - name: outer
    summary: Az alkalmazni kívánt második függvény.
    isFunction: true
    input:
      types:
      - uid: "'U"
        isLocal: true
    output:
      types:
      - uid: "'V"
        isLocal: true
  - name: inner
    summary: Az elsőként alkalmazandó függvény.
    isFunction: true
    input:
      types:
      - uid: "'T"
        isLocal: true
    output:
      types:
      - uid: "'U"
        isLocal: true
output:
  content: ('T -> 'V)
  types:
  - summary: Egy új függvény $h $, amely minden bemenethez $x $, $f (g (x)) = h (x) $.
    isFunction: true
    input:
      types:
      - uid: "'T"
        isLocal: true
    output:
      types:
      - uid: "'V"
        isLocal: true
typeParameters:
- uid: "'T"
  summary: Az elsőként alkalmazandó függvény bemeneti típusa.
- uid: "'U"
  summary: Az elsőként alkalmazandó függvény kimeneti típusa és az alkalmazandó második függvény bemeneti típusa.
- uid: "'V"
  summary: Az alkalmazni kívánt második függvény kimeneti típusa.
metadata:
  ms.openlocfilehash: 69fbd6a4fafbc61a63e41257b7100303fd48d4d4
  ms.sourcegitcommit: edcf15044d7bdf4f8b21fb8f6af4bde475eb13a0
  ms.translationtype: MT
  ms.contentlocale: hu-HU
  ms.lasthandoff: 11/05/2019
  ms.locfileid: "73223071"
